# render.yaml

services:
  - type: web
    name: javic-backend
    env: node
    plan: free
    buildCommand: "yarn install"
    startCommand: "node backend/server.js"
    envVars:
      - key: MONGO_URI
        value: <tu_mongo_uri>
      - key: PORT
        value: 5000
